FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /home

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    git \
    cmake \
    ninja-build \
    make \
    python3 \
    gdb \
    gcc-12 g++-12 \
    gcc-arm-none-eabi g++-arm-none-eabi \
    clang-16 llvm-16 compiler-rt-16 \
    && rm -rf /var/lib/apt/lists/*

RUN ln -sf /usr/bin/gcc-12 /usr/bin/gcc \
 && ln -sf /usr/bin/g++-12 /usr/bin/g++

